version: '3'
services:
  
  db:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      - SA_PASSWORD=SqlServer.1
      - ACCEPT_EULA=y
    ports:
      - 1434:1433
    volumes:
    - ./database:/var/opt/backups
